name: SmartBudget
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  path: any

  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.4
  fluttertoast: ^8.2.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^16.3.2
  photo_view: ^0.14.0
  provider: ^6.0.1
  intl: ^0.19.0
  sqflite: ^2.2.8+2
  month_year_picker: ^0.4.0+1
  flutter_speed_dial: ^7.0.0
  events_emitter: ^0.5.2
  sqflite_common_ffi: ^2.2.5
  flutter_bloc: ^8.1.3
  currency_picker: ^2.0.16
  material_symbols_icons: ^4.2741.0
  cached_network_image: ^3.3.1
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/currencies.json
    - assets/images/

environment:
  sdk: ">=2.17.6 <3.0.0"